// generator/services/seed/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import { LoginService } from '../login/login.service';
import { Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators, FormControl } from '@angular/forms';
@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.scss']
})
export class SignupComponent implements OnInit {
  public user: any = {
    firstName: '',
    lastName: '',
    email: '',
    password: '',
  };
  public show: boolean;
  public signupform: FormGroup;
  public socialSignup: Boolean = false;
  public submit;



  constructor(
    private loginService: LoginService,
    private router: Router
  ) {
    this.show = false;

  }

  ngOnInit() {
    this.signupform = new FormGroup({
      signupdata: new FormGroup({
        firstname: new FormControl(null, [Validators.required]),
        lastname: new FormControl(null, [Validators.required]),
        email: new FormControl(null, [Validators.required, Validators.email]),
        password: new FormControl(null, [Validators.required, Validators.pattern('(?=.*[a-z])(?=.*[A-Z])(?=.*[0-8])(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&].{7,}')])
      })
    });
  }

  signup() {
    this.submit = true;

    // stop here if form is invalid
    if (this.signupform.invalid) {
      return;
    }
    const singupinfo = {
      firstName: this.signupform.value.signupdata.firstname,
      lastName: this.signupform.value.signupdata.lastname,
      email: this.signupform.value.signupdata.email,
      password: this.signupform.value.signupdata.password
    };
    this.loginService.signup(singupinfo).subscribe(data => {
      this.router.navigate(['login']);
    });
  }

  hideEye() {
    this.show = !this.show;
  }

}

<div class="background-images">
  <div class="container left_align">
    <div class="row">
      <div class="col-lg-4"></div>
      <div class="col-lg-4">
        <div class="main">
          <div class="geppetto-img">
            <img src="../../assets/img/Group2704.png">
          </div>
          <h3 class="signup-text-color">Please {{'source.register' | i18next}}</h3>
          <form [formGroup]="signupform">
            <div formGroupName="signupdata">
              <div class="form-group">
                <label class="text">First Name</label>
                <input type="text" class="form-control center" formControlName="firstname" placeholder="First Name">
                <span *ngIf="!signupform.get('signupdata.firstname').valid && signupform.get('signupdata.firstname').touched || !signupform.get('signupdata.firstname').valid && submit"
                  class="invalid-feedback">
                  *Required
                </span>
              </div>
              <div class="form-group">
                <label class="text">Last Name</label>
                <input type="text" class="form-control center" formControlName="lastname" placeholder="Last Name">
                <span *ngIf="!signupform.get('signupdata.lastname').valid && signupform.get('signupdata.lastname').touched || !signupform.get('signupdata.lastname').valid && submit "
                  class="invalid-feedback">
                  *Required
                </span>
              </div>
              <div class="form-group">
                <label class="text">Email</label>
                <input type="email" class="form-control center" formControlName="email" placeholder="Email">
                <span *ngIf="!signupform.get('signupdata.email').valid && signupform.get('signupdata.email').touched || !signupform.get('signupdata.email').valid && submit" 
                  class="invalid-feedback">
                  Must be a valid Email Id
                </span>
              </div>
              <div class="form-group">
                <label class="text">Password</label>
                <input type="password" class="form-control center" formControlName="password" placeholder="Password"
                  [type]="show ? 'text' : 'password'" pw-show-hide="icon" (keyup.enter)="signup()">
                <div class="input-group-append align-right">
                  <span class="input-group-text general-input"><img
                      [src]="show ? '../../assets/img/eyeopen.png' : '../../assets/img/eyeslash.png'" height="20"
                      (click)="hideEye()" alt="eye" /></span>
                </div>
                <span *ngIf="!signupform.get('signupdata.password').valid && signupform.get('signupdata.password').touched || !signupform.get('signupdata.password').valid && submit"
                  class="invalid-feedback">
                  A Password must be 8 character and must have a Uppercase , Lowercase and a Special character
                </span>
              </div>
            </div>
            <div class="center">
              <button class="btn btn login signup-button-color" (click)="signup()">
                {{'source.submit' | i18next}}
              </button>
            </div>
            <div class="rigister">
              <p class="center signup-text-color">{{'source.alreadyReg' | i18next}}? <a routerLink="/login">{{'source.loginHere' | i18next}}</a></p>
            </div>
          </form>
        </div>
        <div class="col-lg-4"></div>
      </div>
      <div class="col-lg-3"></div>
    </div>
</div>

// generator/services/seed/reactBase/src/app/signup/signup.tsx
import React, { useEffect, useState } from "react";
import "./signup.scss";
import axios from 'axios';
import { Button, Form, FormGroup, Label, Input, FormText,  } from "reactstrap";
import { register } from '../login/login.services';
import logo from '../../assets/img/Group2704.png';

const Signup = (props:any) => {
  
  const [formData, setFormData] = useState({
    firstName: '',
    lastName: '',
    email: '',
    password: '',
  });

  const { firstName, lastName, email, password } = formData;

  const onChange = (e:any) => setFormData({ ...formData, [e.target.name]: e.target.value });

  const onSubmit = async (e:any) => {
      e.preventDefault();
      console.log(formData);
      register(formData);
      

  };

  useEffect(() => {

  });

  return (
    <div className="background-images">
      <div className="container left_align">
        <div className="row">
          <div className="col-lg-4"></div>
          <div className="col-lg-4">
            <div className="main">
              <div className="geppetto-img">
                <img src={logo}/>
              </div>
                <div className="login-Wrappe text-left ">
                  <h3 className="login-title">Please Register</h3>
                  <div className="text-align-left">
                    <Form onSubmit={e => onSubmit(e)}>
                      <FormGroup>
                        <Label className="login-label" for="firstname">
                          First Name
                        </Label>
                        <Input
                          className="login-input"
                          type="text"
                          name="firstName"
                          value={firstName}
                          id="firstname"
                          placeholder="First Name"
                          onChange={e => onChange(e)}
                        />
                      </FormGroup>
                      <FormGroup>
                        <Label className="login-label" for="lastname">
                          Last Name
                        </Label>
                        <Input
                          className="login-input"
                          type="text"
                          name="lastName"
                          value={lastName}
                          id="lastname"
                          placeholder="Last Name"
                          onChange={e => onChange(e)}
                        />
                      </FormGroup>
                      <FormGroup>
                        <Label className="login-label" for="email">
                          Email
                        </Label>
                        <Input
                          className="login-input"
                          type="text"
                          name="email"
                          value={email}
                          id="email"
                          pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$"
                          placeholder="Email"
                          onChange={e => onChange(e)}
                        />
                      </FormGroup>
                      <FormGroup>
                        <Label className="login-label" for="password">
                          Password
                        </Label>
                        <Input
                          className="login-input"
                          type="password"
                          name="password"
                          value={password}
                          id="password"
                          pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"
                          placeholder="password"
                          onChange={e => onChange(e)}
                        />
                      </FormGroup>
                      <div className="text-center mb-3">
                        <Button className="login-btn-width">Submit</Button>
                      </div>
                    </Form>
                  </div>
                  <span className="signup-text-color">Already Registered? <span className="span-text-link" onClick={()=>props.history.push("/login")}>Login Here</span></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  );
};
export default Signup;
