// generator/services/seed/reactBase/src/app/user/profilesettings/profilesettings.tsx
import React from "react";
import "./profilesettings.scss";

class ProfileSettings extends React.Component{
    render(){
        return(
            <div className="profileform">
                <form>
                    <div className="row">
                        <div className="col-sm-6">
                            <div className="form-group">
                                <label className="label"><strong>First Name</strong></label>
                                <input type="text" className="form-control" placeholder="Firstname" name="firstname"/>
                            </div>
                        </div>
                        <div className="col-sm-6">
                            <div className="form-group">
                                <label className="label"><strong>Last Name</strong></label>
                                <input type="text" className="form-control" placeholder="Lastname" name="lastname"/>
                            </div>
                        </div>
                        <div className="col-sm-6">
                            <div className="form-group">
                                <label className="label"><strong>User Name</strong></label>
                                <input type="text" className="form-control" placeholder="Username" name="username"/>
                            </div>
                        </div>
                        <div className="col-sm-6">
                            <div className="form-group">
                                <label className="label"><strong>Password</strong></label>
                                <input type="text"  className="form-control" placeholder="Password" name="password"/>
                            </div>
                        </div>
                        <div className="col-sm-6">
                            <div className="form-group">
                                <label className="label"><strong>Email</strong></label>
                                <input type="email" className="form-control" placeholder="Email" name="email"/>
                            </div>
                        </div>
                        <div className="col-sm-6">
                            <div className="form-group">
                                <label className="label"><strong>Installer Token</strong></label>
                                <input type="text" className="form-control" placeholder="Installr Token" name="installrToken"/>
                            </div>
                        </div>
                        <div className="col-sm-6">

                        </div>
                        <div className="col-sm-6">
                            <button type="submit" className="btn btn-primary" >Save</button>&nbsp;&nbsp;
                            <button type="submit" className="btn btn-primary" >cancel</button>
                        </div>
                    </div>
                </form>
            </div>
        );
    }
}

// application/clients/desktop/src/app/user/profilesettings/profilesettings.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { UserService } from '../user.service';

@Component({
  selector: 'app-profilesettings',
  templateUrl: './profilesettings.component.html',
  styleUrls: ['./profilesettings.component.scss']
})
export class ProfilesettingsComponent implements OnInit {

  constructor(private router: ActivatedRoute, private profileservice: UserService, private route: Router) { }

  public id: any;
  public Userobject = {
    'firstname': '',
    'lastname': '',
    'email': '',
    'role': {},
    'id': '',
    'username': ''
  };
  public roles: any[] = [];
  public rolechange: any;

  ngOnInit() {
    this.Queryparams();
  }

  Queryparams() {
    this.router.queryParams.subscribe(params => {
      this.id = params['id'];
    });
    this.Userdetails();
  }

  Userdetails() {
    this.profileservice.Getuser(this.id).subscribe(data => {
      const user = data.body;
      this.Userobject.firstname = user.firstname;
      this.Userobject.lastname = user.lastname;
      this.Userobject.email = user.email;
      this.Userobject.role = user.role.role;

      this.profileservice.Getroles().subscribe(roledata => {
        this.roles = roledata.body;
        console.log('-------roles----->>>>', this.Userobject.role);
        const index = this.roles.findIndex(x => x.role === this.Userobject.role);
        console.log('-------indexvalue-----', index);
        if (index > -1) {
          this.roles.splice(index, 1);
        }
        console.log('-------roles--array--->>>>', this.roles);
      }, error => {
        console.error('error:', error);
      });
    }, error => {
      console.error('error:', error);
    });
  }

  onChange(event) {
    this.rolechange = '';
    console.log('selected  event---->>>', event);

    const updaterole = this.roles.find(x => x.role === event);

    console.log('------roledetails---->>>>', updaterole);

    this.rolechange = updaterole;
  }

  Updateuser() {
    this.Userobject.role = this.rolechange;
    this.Userobject.id = this.id;
    this.Userobject.username = this.Userobject.email;
    console.log('---------updateuserdetails-----', this.Userobject);
    this.profileservice.Updateuser(this.Userobject).subscribe(data => {
      this.route.navigate(['admin']);
    }, error => {
      console.error('error:', error);
    });
  }
}

<div class="profileform">
  <form>
    <div class="row">
      <div class="col">
        <label class="label"><strong>First Name</strong></label>
        <input type="text" class="form-control" placeholder="Firstname" [(ngModel)]='Userobject.firstname'
          name="firstname">
      </div>
      <div class="col">
        <label class="label"><strong>Last Name</strong></label>
        <input type="text" class="form-control" placeholder="Lastname" [(ngModel)]='Userobject.lastname'
          name="lastname">
      </div>
    </div>
    <br>
    <div class="form-group">
      <label class="label"><strong>User Name</strong></label>
      <input type="text" class="form-control" [disabled]="true" placeholder="Username" [(ngModel)]='Userobject.username'
        name="username">
    </div>
    <div class="form-group">
      <label class="label"><strong>Password</strong></label>
      <input type="text" readonly class="form-control" placeholder="Password" [(ngModel)]='Userobject.password'
        name="password">
    </div>
    <div class="form-group">
      <label class="label"><strong>Email</strong></label>
      <input type="email" class="form-control" placeholder="Email" [(ngModel)]='Userobject.email' name="email">
    </div>
    <div class="form-group">
      <label class="label"><strong>Installer Token</strong></label>
      <input type="text" class="form-control" placeholder="Installr Token" [(ngModel)]='Userobject.installrToken'
        name="installrToken">
    </div>
    <div class="form-group">
      <label class="label"><strong>Role</strong></label>
      <select class="form-control" (change)="onChange($event.target.value)">
        <option value="" selected>Select Roles</option>
        <option *ngFor="let rolevalue of roles">{{rolevalue.role}}</option>
      </select>
    </div>
    <div style="float: right">
      <button type="submit" class="btn btn-primary" (click)="Updateuser(Userobject)">Save</button>&nbsp;&nbsp;
      <button type="submit" class="btn btn-primary" (click)="cancle()">cancel</button>
    </div>

  </form>
</div>
